import { StyleSheet } from 'react-native';
import { Fonts } from '../../styles';

const styles = StyleSheet.create({
  calendarContainer: {
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    padding: 8,
  },
  TextStyle: {
    fontSize: 18,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 24,
    letterSpacing: -0.17,
    textAlign: 'center',
    marginTop: 20,
  },
  yearSelectedStyle: {
    height: 60,
    width: 60,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    fontSize: 21,
    fontWeight: '400',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    paddingVertical: 10,
    marginRight: 10,
    color: '#44475B',
  },
  unselectedStyle: {
    height: 40,
    width: 40,
    fontFamily: Fonts.type.gotham_medium,
    fontSize: 13,
    fontWeight: '500',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: 'rgba(0, 0, 0, 0.5)',
    paddingVertical: 10,
    marginRight: 10,
    borderRadius: 25,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    marginVertical: 5,
  },
  selectedStyle: {
    height: 40,
    width: 40,
    borderRadius: 25,
    borderStyle: 'solid',
    backgroundColor: '#00D09C',
    borderWidth: 1,
    borderColor: '#dfe1e4',
    fontFamily: Fonts.type.gotham_medium,
    fontSize: 13,
    fontWeight: '500',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: '#FFFFFF',
    paddingVertical: 10,
    marginBottom: 4,
    marginRight: 10,
    overflow: 'hidden',
  },
  marginVertical20: { marginVertical: 20 },
  monthYearContainer: {
    alignSelf: 'center',
    width: 300,
    paddingHorizontal: 20,
  },
  yearElement: {
    width: 60,
    alignSelf: 'center',
  },
  marginHorizontal30: { marginHorizontal: 30 },
  monthView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingHorizontal: 25,
  },
  dateView: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  dateElement: {
    justifyContent: 'center',
    borderRadius: 18,
    margin: 3,
    height: 36,
    width: 36,
  },
  textAlignCenter: {
    textAlign: 'center',
  },
  arrowIcon: {
    height: 32,
    width: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  alignItemsCenter: { alignItems: 'center' },
  alignItemsStart: { alignItems: 'flex-start' },
  dayMonthView: {
    height: 40,
    flexDirection: 'row',
    paddingHorizontal: 30,
    alignItems: 'center',
    marginBottom: 16,
  },
  activeMonthTitle: {
    flex: 2,
    textAlign: 'center',
    fontSize: 16,
  },
});

export default styles;
