module.exports = {
  someSidebar: {
    'Geting Started': ['installation', 'contributing'],
    Components: [
      'button',
      'checkbox',
      'numpad',
      'codeinput',
      // 'popup',
      'radiobutton',
      'radioGroup',
      'table',
      'emptyview',
      // 'calendar',
      // 'slider',
      'switch',
      'dropdown',
      'input',
      'draggableList',
      'searchbar',
      // 'infobox',
      // 'ticker',
      /* next_doc_id */
    ],
    Theme: [
      'overview',
      'themeprovider',
      'themecontext',
      'useColors',
      'useThemeToggle',
      'useTheme',
      'withTheme',
    ],
    Layouts: ['bottomfixedview', 'centeredview'],
    // Guides: ['Contributing',''],
  },
};
